name: Bump version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0

      - name: Install Conventional Commits
        run: npm install conventional-changelog-conventionalcommits -D

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v2.6.0
        with:
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

